export const ADD_FAVOURITES = "ADD_FAVOURITES";
export const REMOVE_FAVOURITES = "REMOVE_FAVOURITES";
export const ADD_FAVOURITE_ITEMS = "ADD_FAVOURITE_ITEMS";
export const REMOVE_FAVOURITE_ITEMS = "REMOVE_FAVOURITE_ITEMS";
